### ISSUE TITLE
Data quality issues

### ISSUE THREAD

**Issue by shaharnoy** [newstatseu/predictions-challenge#1]
Hi Team,

There are 24 lines in the dataset that has DQ issues where the total points do not agree to the stats representation:

League	|	GAME	|	TEAM	|	2P	|	3P	|	FT	|	PTS	|	difference_ptsToStats
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
League1	|	game_11	|	team_1	|	2	|	3	|	17	|	69	|	-2
League1	|	game_12	|	team_6	|	2	|	3	|	21	|	76	|	-2
League1	|	game_14	|	team_10	|	2	|	3	|	22	|	91	|	-2
League1	|	game_27	|	team_5	|	2	|	3	|	14	|	79	|	-2
League1	|	game_29	|	team_14	|	2	|	3	|	9	|	81	|	-2
League1	|	game_29	|	team_7	|	2	|	3	|	15	|	69	|	-2
League1	|	game_38	|	team_3	|	2	|	3	|	11	|	76	|	2
League2	|	game_3	|	team_10	|	2	|	3	|	15	|	60	|	-12
League2	|	game_3	|	team_6	|	2	|	3	|	11	|	72	|	4
League2	|	game_4	|	team_8	|	2	|	3	|	16	|	75	|	-4
League2	|	game_6	|	team_16	|	2	|	3	|	17	|	65	|	6
League2	|	game_7	|	team_4	|	2	|	3	|	27	|	75	|	2
League2	|	game_8	|	team_11	|	2	|	3	|	19	|	85	|	-2
League2	|	game_8	|	team_15	|	2	|	3	|	16	|	84	|	-2
League2	|	game_9	|	team_8	|	2	|	3	|	22	|	101	|	-2
League2	|	game_10	|	team_9	|	2	|	3	|	16	|	78	|	-1
League2	|	game_14	|	team_3	|	2	|	3	|	8	|	58	|	-8
League2	|	game_15	|	team_13	|	2	|	3	|	15	|	75	|	-15
League2	|	game_19	|	team_7	|	2	|	3	|	15	|	83	|	2
League2	|	game_22	|	team_2	|	2	|	3	|	12	|	76	|	4
League2	|	game_22	|	team_6	|	2	|	3	|	20	|	80	|	2
League2	|	game_27	|	team_10	|	2	|	3	|	17	|	78	|	-3
League2	|	game_29	|	team_1	|	2	|	3	|	11	|	88	|	-1
League2	|	game_34	|	team_10	|	2	|	3	|	6	|	58	|	-6

BR,
Shahar

**Comment by dev-newstatseu** [comment]
Good catch! Let me investigate and get back to you!

**Comment by dev-newstatseu** [comment]
@shaharnoy have a look on the last push and let me know
should be fixed now

**Comment by shaharnoy** [comment]
@dev-newstatseu - Perfect, Looks good!
